CREATE TABLE CNAES (
    CODIGO CHAR(7) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE MUNICIPIOS (
    CODIGO CHAR(4) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE NATUREZAS (
    CODIGO CHAR(4) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE PAISES (
    CODIGO CHAR(3) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE QUALIFICACOES (
    CODIGO CHAR(2) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE EMPRESAS (
    CNPJ_BASICO CHAR(8) NOT NULL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    NATUREZA_JURIDICA CHAR(4) NOT NULL,
    QUALIFICACAO_RESPONSAVEL CHAR(2) NOT NULL,
    CAPITAL_SOCIAL DECIMAL(15, 2) NOT NULL,
    PORTE_EMPRESA CHAR(2) NOT NULL,
    ENTE_FEDERATIVO_RESPONSAVEL VARCHAR(255),
    FOREIGN KEY (NATUREZA_JURIDICA) REFERENCES NATUREZAS(CODIGO),
    FOREIGN KEY (QUALIFICACAO_RESPONSAVEL) REFERENCES QUALIFICACOES(CODIGO)
);

CREATE TABLE ESTABELECIMENTOS (
    CNPJ_BASICO CHAR(8) NOT NULL,
    CNPJ_ORDEM CHAR(4) NOT NULL,
    CNPJ_DV CHAR(2) NOT NULL,
    IDENTIFICADOR_MATRIZ_FILIAL CHAR(1) NOT NULL,
    NOME_FANTASIA VARCHAR(255),
    SITUACAO_CADASTRAL CHAR(2) NOT NULL,
    DATA_SITUACAO_CADASTRAL DATE,
    MOTIVO_SITUACAO_CADASTRAL CHAR(2),
    NOME_CIDADE_EXTERIOR VARCHAR(255),
    PAIS CHAR(3),
    DATA_INICIO_ATIVIDADE DATE,
    CNAE_FISCAL_PRINCIPAL CHAR(7) NOT NULL,
    CNAE_FISCAL_SECUNDARIA VARCHAR(255),
    TIPO_LOGRADOURO VARCHAR(50),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255),
    CEP CHAR(8),
    UF CHAR(2),
    MUNICIPIO CHAR(4),
    DDD_1 CHAR(2),
    TELEFONE_1 CHAR(10),
    DDD_2 CHAR(2),
    TELEFONE_2 CHAR(10),
    DDD_FAX CHAR(2),
    FAX CHAR(10),
    CORREIO_ELETRONICO VARCHAR(255),
    SITUACAO_ESPECIAL VARCHAR(50),
    DATA_SITUACAO_ESPECIAL DATE,
    PRIMARY KEY (CNPJ_BASICO, CNPJ_ORDEM, CNPJ_DV),
    FOREIGN KEY (CNPJ_BASICO) REFERENCES EMPRESAS(CNPJ_BASICO),
    FOREIGN KEY (CNAE_FISCAL_PRINCIPAL) REFERENCES CNAES(CODIGO),
    FOREIGN KEY (PAIS) REFERENCES PAISES(CODIGO),
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIOS(CODIGO)
);

CREATE TABLE SIMPLES (
    CNPJ_BASICO CHAR(8) NOT NULL,
    OPCAO_PELO_SIMPLES CHAR(1),
    DATA_OPCAO_PELO_SIMPLES DATE,
    DATA_EXCLUSAO_DO_SIMPLES DATE,
    OPCAO_PELO_MEI CHAR(1),
    DATA_OPCAO_PELO_MEI DATE,
    DATA_EXCLUSAO_DO_MEI DATE,
    PRIMARY KEY (CNPJ_BASICO),
    FOREIGN KEY (CNPJ_BASICO) REFERENCES EMPRESAS(CNPJ_BASICO)
);

CREATE TABLE SOCIOS (
    CNPJ_BASICO CHAR(8) NOT NULL,
    IDENTIFICADOR_SOCIO CHAR(1) NOT NULL,
    NOME_SOCIO VARCHAR(255) NOT NULL,
    CNPJ_CPF_SOCIO VARCHAR(14),
    QUALIFICACAO_SOCIO CHAR(2) NOT NULL,
    DATA_ENTRADA_SOCIEDADE DATE,
    PAIS CHAR(3),
    REPRESENTANTE_LEGAL VARCHAR(11),
    NOME_REPRESENTANTE VARCHAR(255),
    QUALIFICACAO_REPRESENTANTE CHAR(2),
    FAIXA_ETARIA CHAR(1),
    PRIMARY KEY (CNPJ_BASICO, IDENTIFICADOR_SOCIO),
    FOREIGN KEY (CNPJ_BASICO) REFERENCES EMPRESAS(CNPJ_BASICO),
    FOREIGN KEY (QUALIFICACAO_SOCIO) REFERENCES QUALIFICACOES(CODIGO),
    FOREIGN KEY (PAIS) REFERENCES PAISES(CODIGO),
    FOREIGN KEY (QUALIFICACAO_REPRESENTANTE) REFERENCES QUALIFICACOES(CODIGO)
);
